echo off
IF "%APP_DEBUG%" GEQ "3" ( ECHO ***********%~n0%~x0***********)
IF NOT "%APP_SETTING_LOADED%"=="1" ( ECHO APP_SETTING is empty & pause & goto :end )

SET COLOR_WHITE=255 255 255
SET COLOR_YELLOW=255 255 0
SET COLOR_BLACK=0 0 0
SET COLOR_ORANGE=247 145 2
SET COLOR_BLUE=2 107 255
SET COLOR_PINK=247 2 104
SET COLOR_PURPLE=133 2 247
SET COLOR_GREEN=2 255 137

SET COLOR_LIGHTORANGE=247 223 211
SET COLOR_LIGHTBLUE=242 247 255

SET COLOR_DARKYELLOW=27 28 0
SET COLOR_DARKBLUE=1 31 48
SET COLOR_DARKPINK=107 20 72
SET COLOR_DARKPURPLE=51 0 51
SET COLOR_DARKGREEN1=25 51 0
SET COLOR_DARKGREEN2=0 51 0
SET COLOR_DARKGREEN3=0 51 25
SET COLOR_DARKGREEN=5 33 0
SET COLOR_DARKYELLOW=51 51 0
SET COLOR_DARKRED=51 0 0

CALL %APP_LIB_STYLE_PATH%\color.bat ~ 0 frgb %COLOR_YELLOW% %COLOR_DARKPURPLE%
CALL %APP_LIB_STYLE_PATH%\color.bat ~ 1 frgb %COLOR_WHITE% %COLOR_DARKPINK%
CALL %APP_LIB_STYLE_PATH%\color.bat ~ 2 frgb %COLOR_WHITE% %COLOR_DARKBLUE%
CALL %APP_LIB_STYLE_PATH%\color.bat ~ 3 frgb %COLOR_WHITE% %COLOR_DARKGREEN2%
CALL %APP_LIB_STYLE_PATH%\color.bat ~ 4 frgb %COLOR_WHITE% %COLOR_DARKYELLOW%


SET COLORINDEX_MAIN=0
SET COLORINDEX_JSON=3
SET COLORINDEX_READLINE=2
SET COLORINDEX_EXEC=1
SET COLORINDEX_GITHUB=4



IF "%APP_DEBUG%" GEQ "2" (
    FOR /l %%A IN (0,1,%ESC_COLOR_INDEX%) DO (
        CALL ECHO Color%%A:%ESC%[%%ESC_COLORS[%%A][0]%%;%%ESC_COLORS[%%A][1]%%mTEST%ESC%[m0
    )
)

:end
    CALL %APP_LIB_STYLE_PATH%\color.bat ~ 0
    IF "%APP_DEBUG%" GEQ "3" ( ECHO ***********END %~n0%~x0***********)