@echo off
SETLOCAL
IF NOT "%APP_SETTING_LOADED%"=="1" CALL %~dp0..\..\settings.bat

REM ECHO str compare ARGS: %*

CALL %APP_LIB_UTILITIES_PATH%\setvariable.bat STR_IN %~1
CALL %APP_LIB_UTILITIES_PATH%\setvariable.bat STR_COMPARE %~2

IF "%~3"=="" (
    SET /A STARTINDEX=0
) ELSE ( 
    SET /A STARTINDEX=%~3
)

IF "%APP_DEBUG%" GEQ "3" ECHO STR_IN: `%STR_IN%`       STR_COMPARE: `%STR_COMPARE%`
CALL %APP_LIB_UTILITIES_PATH%\strlen.bat "%STR_COMPARE%" COMPARELEN

:: DEBUG
CALL SET SUBSTR=%%STR_IN:~%STARTINDEX%,%COMPARELEN%%%
IF "%APP_DEBUG%" GEQ "3" ECHO Start,len: %STARTINDEX%,%COMPARELEN%  & ECHO P:`%SUBSTR%`=`%STR_COMPARE%`

IF [%SUBSTR%]==[%STR_COMPARE%] (
    :: MATCH
    REM ECHO MATCH "!STR_COMPARE:~%STARTINDEX%,%COMPARELEN%!"="%STR_COMPARE%"
    ENDLOCAL
    exit /b 1
)

:: NOT MATCH
ENDLOCAL
exit /b 0