echo off

IF "%~1"=="-1" (
    SET /A ESC_BGCOLOR_INDEX-=1
    CALL SET ESC_BGCOLOR=%%ESC_BGCOLORS[!ESC_BGCOLOR_INDEX!]%%
    echo %ESC%!ESC_BGCOLOR! PREV BGCOLOR from !ESC_BGCOLOR_INDEX! as !ESC_BGCOLOR! 
    exit /B 0
)
IF "%~1"=="+1" (
    SET /A ESC_BGCOLOR_INDEX+=1
    CALL SET ESC_BGCOLOR=%%ESC_BGCOLORS[!ESC_BGCOLOR_INDEX!]%%
    echo %ESC%!ESC_BGCOLOR! echo NEXT BGCOLOR from !ESC_BGCOLOR_INDEX! as !ESC_BGCOLOR! 
    exit /B 0
)
IF "%~1"=="~" (
    SET /A ESC_BGCOLOR_INDEX=%~2
    CALL SET ESC_BGCOLOR=%%ESC_BGCOLORS[!ESC_BGCOLOR_INDEX!]%%
    echo %ESC%!ESC_BGCOLOR! SET BGCOLOR from !ESC_BGCOLOR_INDEX! as !ESC_BGCOLOR! 
    exit /B 0
)

SET ESC_BGCOLOR=%~1
SET /A ESC_BGCOLOR_INDEX+=1
SET ESC_BGCOLORS[!ESC_BGCOLOR_INDEX!]=%ESC_BGCOLOR%
echo %ESC%%ESC_BGCOLOR% new BGCOLOR %ESC_BGCOLOR% added on !ESC_BGCOLOR_INDEX!


exit /b 0